# Generated by Django 5.0.2 on 2024-05-04 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_coupon_order_final_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='original_total_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
