# Generated by Django 5.0.2 on 2024-05-04 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_original_total_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discounted_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
