# Generated by Django 5.0.2 on 2024-05-10 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_coupon_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='status',
            new_name='payment_status',
        ),
    ]
