# Generated by Django 5.0.2 on 2024-05-24 11:44

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_coupon_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoffers',
            name='end_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2024, 5, 24))]),
        ),
        migrations.AlterField(
            model_name='productoffers',
            name='start_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2024, 5, 24))]),
        ),
    ]
