# Generated by Django 5.0.2 on 2024-05-29 12:13

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_alter_productoffers_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'COD'), ('Paypal', 'PAYPAL'), ('Wallet', 'Wallet'), ('Wallet and paypal', 'Wallet and Paypal')], default='COD', max_length=100),
        ),
        migrations.AlterField(
            model_name='productoffers',
            name='end_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2024, 5, 29))]),
        ),
        migrations.AlterField(
            model_name='productoffers',
            name='start_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2024, 5, 29))]),
        ),
    ]
