# Generated by Django 5.0.2 on 2024-06-07 07:26

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_alter_productoffers_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoffers',
            name='end_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2024, 6, 7))]),
        ),
        migrations.AlterField(
            model_name='productoffers',
            name='start_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2024, 6, 7))]),
        ),
    ]
