# Generated by Django 5.0.2 on 2024-06-09 11:07

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_alter_order_address_line_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoffers',
            name='end_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2024, 6, 9))]),
        ),
        migrations.AlterField(
            model_name='productoffers',
            name='start_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2024, 6, 9))]),
        ),
    ]
