# Generated by Django 5.0.2 on 2024-05-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_reviewrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discprice',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=15),
        ),
    ]
