# Generated by Django 5.0.2 on 2024-05-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_discprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='Discount Percentage'),
        ),
    ]
